### ISSUE TITLE
logspam (TypeErrors and DecimalErrors)

### ISSUE THREAD

**Issue by Efreak** [angarg12/TrueExponential#7]
[Console screenshot here](http://i.imgur.com/vtDaO9v.png)

Log gets spammed as soon as page finishes loading. I'm using Google Chrome (either beta or dev, so I can use userscripts and plugins not from the store).

**Comment by Efreak** [comment]
I'm guessing this is related to [the broken progress bar](http://i.imgur.com/fQaZi1l.png).

Also, somehow I doubt this is supposed to be entirely unstyled, seeing as you actually _have_ a progress bar?

Edit: resetting my save fixed the logspam, however the original log error is still there.

**Comment by angarg12** [comment]
Hello,
I have a save check function that wipes older saves in order to prevent backward incompatibility, but it seems that I missed updating it to the latest version. Will fix.

Regarding the console error, the only one I get right now is this one:

```
"Error: number is undefined
prettifyNumber@http://angarg12.github.io/TrueExponential/js/exponential.js:150:1
```

Which seems to go away as soon as the whole script is loaded (I will check it out nevertheless).
